### ISSUE TITLE
Intermittent issue while trying to sync community devsec.hardening collection

### ISSUE THREAD

**Issue by newswangerd** [pulp/pulp_ansible#773] opened 2021-12-16 21:09 UTC
Original issue: https://issues.redhat.com/browse/AAH-1202

**Comment by newswangerd** [comment] 2022-01-19 16:25
Affects galaxy_ng 4.4.0 and pulp ansible 0.11.1

**Comment by bmbouter** [comment] 2022-01-19 16:42
What versions of pulpcore and pulp_ansible should we test against?

**Comment by newswangerd** [comment] 2022-01-19 17:01
Pulpcore 3.15.0 and pulp ansible 0.10.1

**Comment by bmbouter** [comment] 2022-01-19 19:20
We should attempt to reproduce this, and then determine (if we can) if [this pulpcore change](https://github.com/pulp/pulpcore/pull/1807) resolves it.

**Comment by mdellweg** [comment] 2022-01-20 13:08
> We should attempt to reproduce this, and then determine (if we can) if [this pulpcore change](https://github.com/pulp/pulpcore/pull/1807) resolves it.

Actually i think this fix needs amendments:
https://github.com/pulp/pulpcore/pull/1851
https://github.com/pulp/pulpcore/pull/2122

**Comment by bmbouter** [comment] 2022-01-24 18:46
@newswangerd which pulpcore versions do these fixes need to go into? Just 3.15.z?

**Comment by newswangerd** [comment] 2022-01-24 19:53
@bmbouter just 3.15.z

**Comment by bmbouter** [comment] 2022-01-26 19:17
Here's a script I used to try to sync galaxy, but it needs rate limiting options added to it:

```
#!/bin/bash

set -ev

repo_name="repo$RANDOM"
remote_name="remote$RANDOM"
url="https://galaxy.ansible.com"
distribution_name="distribution$RANDOM"
base_path="$RANDOM"

pulp ansible remote -t collection create --name $remote_name --url $url
pulp ansible repository create --name $repo_name --remote $remote_name
pulp ansible repository sync --name $repo_name

echo "Created and synced repo $repo_name"
```

It fails very quickly with: `failed: '429, message='Too Many Requests', url=URL('https://galaxy.ansible.com/api/v2/collections/kbreit/meraki/')'`. This is on a system where I `pip install pulp_ansible==0.10.1`.

**Comment by bmclaughlin** [comment] 2022-01-26 19:47
The default rate limiting options we use in galaxy_ng are:
download concurrency = 10
rate limit = 8

**Comment by bmbouter** [comment] 2022-01-26 19:52
thanks @bmclaughlin I've revised [the reproducer](https://github.com/pulp/pulp_ansible/issues/773#issuecomment-1022516894) to use those values and I'm rerunning the full mirror now.

**Comment by bmbouter** [comment] 2022-01-26 20:31
Well I didn't get the exception of interest, but I did get a failure. I got this:

```
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]: pulp [42527f144b314854a96714c904237add]: pulpcore.tasking.pulpcore_worker:INFO: Task c1c4a3a2-0883-4371-bb19-302b6768d5f6 failed ('NoneType' object has no attribute 'get')
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]: pulp [42527f144b314854a96714c904237add]: pulpcore.tasking.pulpcore_worker:INFO:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulpcore/tasking/pulpcore_worker.py", line 370, in _perform_task
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     result = func(*args, **kwargs)
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulp_ansible/app/tasks/collections.py", line 145, in sync
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     repo_version = d_version.create()
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulpcore/plugin/stages/declarative_version.py", line 161, in create
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     loop.run_until_complete(pipeline)
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     return future.result()
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulpcore/plugin/stages/api.py", line 225, in create_pipeline
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     await asyncio.gather(*futures)
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulpcore/plugin/stages/api.py", line 43, in __call__
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     await self.run()
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulpcore/plugin/stages/content_stages.py", line 168, in run
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     await sync_to_async(process_batch)()
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     ret = await asyncio.wait_for(future, timeout=None)
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/lib64/python3.9/asyncio/tasks.py", line 442, in wait_for
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     return await fut
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     result = self.fn(*self.args, **self.kwargs)
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/asgiref/sync.py", line 455, in thread_handler
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     return func(*args, **kwargs)
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulpcore/plugin/stages/content_stages.py", line 166, in process_batch
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     self._post_save(batch)
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:   File "/usr/local/lib/pulp/lib64/python3.9/site-packages/pulp_ansible/app/tasks/collections.py", line 912, in _post_save
Jan 26 20:29:24 pulp3-source-fedora34.localhost.example.com pulpcore-worker[43871]:     collection_version.requires_ansible = runtime_yaml.get("requires_ansible")
```

**Comment by bmbouter** [comment] 2022-01-26 21:39
I received the same exception again. I believe there is a data quality issue on galaxy.ansible.com that our code is not adequately handling.

**Comment by bmbouter** [comment] 2022-01-27 15:10
I moved that issue to it's own issue here to track it's fix separately. It's not the same root cause as the claim in this bug. https://github.com/pulp/pulp_ansible/issues/806

**Comment by mdellweg** [comment] 2022-01-27 17:41
> Pulpcore 3.15.0 and pulp ansible 0.10.1

Trying to install from the git tags:
```
ERROR: Cannot install pulp-ansible==0.10.1 and pulpcore 3.15.0 (from /home/vagrant/devel/pulpcore) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pulpcore 3.15.0 (from /home/vagrant/devel/pulpcore)
    pulp-ansible 0.10.1 depends on pulpcore<3.17 and >=3.15.1
```
How sure are you about those numbers?

**Comment by bmbouter** [comment] 2022-01-27 17:42
Yeah when I installed `pulp_ansible==0.10.1` I actually received `pulpcore==3.16.2`

**Comment by mdellweg** [comment] 2022-01-27 19:03
I will try to reproduce with this snippet now:
```sh
#!/bin/bash

set -ev

for i in $(seq 100)
do
    repo_name="repo$RANDOM"
    remote_name="remote$RANDOM"
    url="https://galaxy.ansible.com"
    distribution_name="distribution$RANDOM"
    base_path="$RANDOM"
    requirements='collections: [devsec.hardening]'

    pulp ansible remote -t collection create --name $remote_name --url $url --download-concurrency 10 --rate-limit 8 --requirements "$requirements"
    pulp ansible repository create --name $repo_name --remote $remote_name
    pulp ansible repository sync --name $repo_name

    echo "Created and synced repo $repo_name"

    pulp ansible content --type collection-version list | jq 'length'

    pulp ansible repository destroy --name "$repo_name"
    pulp ansible remote destroy --name "$remote_name"
    pulp orphan cleanup --protection-time 0
done
```
Versions:
```json
{
      "component": "core",
      "version": "3.16.0"
    },
    {
      "component": "certguard",
      "version": "1.6.0.dev"
    },
    {
      "component": "herminig",
      "version": "0.1.0a1.dev"
    },
    {
      "component": "file",
      "version": "1.10.1"
    },
    {
      "component": "deb",
      "version": "2.15.1"
    },
    {
      "component": "container",
      "version": "2.9.1"
    },
    {
      "component": "ansible",
      "version": "0.10.1"
    }
```

**Comment by bmbouter** [comment] 2022-01-28 18:01
I was able to sync all collections on galaxy.ansible.com (13488 collectionVersions) in 1 hour and 24 minutes with no errors. I have not been able to reproduce the issue. I'm going to close this issue while awaiting more info on a reproducer.

**Closed by bmbouter** 2022-01-28 18:01 UTC
